FROM node:20-alpine

WORKDIR /app

# Dependencies installieren
COPY package*.json ./
RUN npm install

# Source rein
COPY tsconfig.json ./
COPY src ./src

# Build
RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
