http:
  middlewares:
    ipallow:
      ipAllowList:
        sourceRange:
          - "192.168.178.0/24" # FritzBox-LAN
          - "172.26.0.5" # Wireguard Container
    crowdsec-bouncer:
      forwardauth:
        address: http://192.168.178.56:3080/api/v1/forwardAuth
        trustForwardHeader: true
  
  serversTransports:
    insecureTransport:
      insecureSkipVerify: true

  services:
    cockpit_pi4:
      loadBalancer:
        servers:
          - url: http://192.168.178.56:9090

    plex:
      loadBalancer:
        servers:
          - url: http://192.168.178.24:32400
    
    nextcloud:
      loadBalancer:
        servers:
          - url: http://192.168.178.24:9001

    truenas:
      loadBalancer:
        servers:
          - url: http://192.168.178.24:8080

    truenas_portainer:
      loadBalancer:
        serversTransport: insecureTransport
        servers:
          - url: https://192.168.178.24:31015

    files:
      loadBalancer:
        serversTransport: insecureTransport
        servers:
          - url: https://192.168.178.24:30044

    tautulli:
      loadBalancer:
        servers:
          - url: http://192.168.178.24:30047

    minio:
      loadBalancer:
        servers:
          - url: http://192.168.178.24:9002

    immich:
      loadBalancer:
        servers:
          - url: http://192.168.178.24:30041

    authentik:
      loadBalancer:
        servers:
          - url: http://192.168.178.24:11080

    gitea:
      loadBalancer:
        servers:
          - url: http://192.168.178.24:9500
    
    ersatztv:
      loadBalancer:
        servers:
          - url: http://192.168.178.24:8409

    cockpit_linux_mini:
      loadBalancer:
        servers:
          - url: http://192.168.178.64:9090

    sparrow:
      loadBalancer:
        servers:
          - url: http://192.168.178.33:9090

    sparrow_portainer:
      loadBalancer:
        serversTransport: insecureTransport
        servers:
          - url: https://192.168.178.33:9443

    firefox_sparrow:
      loadBalancer:
        servers:
          - url: http://192.168.178.24:5801

    jdownloader_sparrow:
      loadBalancer:
        servers:
          - url: http://192.168.178.24:5802

    overseerr:
      loadBalancer:
        servers:
          - url: http://192.168.178.24:5055

    radarr:
      loadBalancer:
        servers:
          - url: http://192.168.178.24:7878

    sonarr:
      loadBalancer:
        servers:
          - url: http://192.168.178.24:8989

    quasarr:
      loadBalancer:
        servers:
          - url: http://192.168.178.24:3011

    coolify:
      loadBalancer:
        servers:
          - url: http://217.154.237.80:8000/

  routers:
    cockpit_pi4_router:
      rule: 'Host(`pi4.example.dev`)'
      service: cockpit_pi4
      entryPoints:
        - https
      middlewares:
        - "ipallow"
      tls:
        certresolver: "letsencrypt"
    
    plex_router:
      rule: 'Host(`plex.example.dev`)'
      service: plex
      entryPoints:
        - https
      tls:
        certresolver: "letsencrypt"
    
    nextcloud_router:
      rule: 'Host(`cloud.example.dev`)'
      service: nextcloud
      entryPoints:
        - https
      middlewares:
      tls:
        certresolver: "letsencrypt"

    immich_router:
      rule: 'Host(`photos.ditz-family.de`)'
      service: immich
      entryPoints:
        - https
      middlewares:
      tls:
        certresolver: "letsencrypt"
    
    authentik_router:
      rule: 'Host(`auth.ditz-family.de`)'
      service: authentik
      entryPoints:
        - https
      middlewares:
      tls:
        certresolver: "letsencrypt"

    truenas_router:
      rule: 'Host(`truenas.example.dev`)'
      service: truenas
      entryPoints:
        - https
      middlewares:
        - "ipallow"
      tls:
        certresolver: "letsencrypt"
    
    tautulli_router:
      rule: 'Host(`tautulli.example.dev`)'
      service: tautulli
      entryPoints:
        - https
      middlewares:
        - "ipallow"
      tls:
        certresolver: "letsencrypt"

    ersatztv_router:
      rule: 'Host(`tv.example.dev`)'
      service: ersatztv
      entryPoints:
        - https
      middlewares:
        - "ipallow"
      tls:
        certresolver: "letsencrypt"

    minio_router:
      rule: 'Host(`blob.example.dev`)'
      service: minio
      entryPoints:
        - https
      middlewares:
        - "ipallow"
      tls:
        certresolver: "letsencrypt"
    
    cockpit_linux_mini_router:
      rule: 'Host(`dev.example.dev`)'
      service: cockpit_linux_mini
      entryPoints:
        - https
      middlewares:
        - "ipallow"
      tls:
        certresolver: "letsencrypt"

    sparrow_router:
      rule: 'Host(`sparrow.example.dev`)'
      service: sparrow
      entryPoints:
        - https
      middlewares:
        - "ipallow"
      tls:
        certresolver: "letsencrypt"

    sparrow_portainer_router:
      rule: 'Host(`portainer.sparrow.example.dev`)'
      service: sparrow_portainer
      entryPoints:
        - https
      middlewares:
        - "ipallow"
      tls:
        certresolver: "letsencrypt"

    firefox_sparrow_router:
      rule: 'Host(`f-vpn.example.dev`)'
      service: firefox_sparrow
      entryPoints:
        - https
      middlewares:
        - "ipallow"
      tls:
        certresolver: "letsencrypt"

    jdownloader_sparrow_router:
      rule: 'Host(`jd-vpn.example.dev`)'
      service: jdownloader_sparrow
      entryPoints:
        - https
      middlewares:
        - "ipallow"
      tls:
        certresolver: "letsencrypt"

    filebrowser_router:
      rule: 'Host(`files.truenas.example.dev`)'
      service: files
      entryPoints:
        - https
      middlewares:
        - "ipallow"
      tls:
        certresolver: "letsencrypt"

    truenas_portainer_router:
      rule: 'Host(`portainer.truenas.example.dev`)'
      service: truenas_portainer
      entryPoints:
        - https
      middlewares:
        - "ipallow"
      tls:
        certresolver: "letsencrypt"

    overseerr_router:
      rule: 'Host(`overseerr.example.dev`)'
      service: overseerr
      entryPoints:
        - https
      middlewares:
      tls:
        certresolver: "letsencrypt"

    radarr_router:
      rule: 'Host(`radarr.example.dev`)'
      service: radarr
      entryPoints:
        - https
      middlewares:
        - "ipallow"
      tls:
        certresolver: "letsencrypt"

    sonarr_router:
      rule: 'Host(`sonarr.example.dev`)'
      service: sonarr
      entryPoints:
        - https
      middlewares:
        - "ipallow"
      tls:
        certresolver: "letsencrypt"

    quasarr_router:
      rule: 'Host(`quasarr.example.dev`)'
      service: quasarr
      entryPoints:
        - https
      middlewares:
        - "ipallow"
      tls:
        certresolver: "letsencrypt"

    gitea_router:
      rule: 'Host(`git.example.dev`)'
      service: gitea
      entryPoints:
        - https
      middlewares:
        - "ipallow"
      tls:
        certresolver: "letsencrypt"

    coolify_router:
      rule: 'Host(`coolify.example.dev`)'
      service: coolify
      entryPoints:
        - https
      middlewares:
        - "ipallow"
      tls:
        certresolver: "letsencrypt"